// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cloudbilling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// CloudBillingClient is the client API for CloudBilling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudBillingClient interface {
	GetServices(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error)
}

type cloudBillingClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudBillingClient(cc grpc.ClientConnInterface) CloudBillingClient {
	return &cloudBillingClient{cc}
}

var cloudBillingGetServicesStreamDesc = &grpc.StreamDesc{
	StreamName: "GetServices",
}

func (c *cloudBillingClient) GetServices(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error) {
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, "/cloudbilling.CloudBilling/GetServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudBillingService is the service API for CloudBilling service.
// Fields should be assigned to their respective handler implementations only before
// RegisterCloudBillingService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type CloudBillingService struct {
	GetServices func(context.Context, *ServicesRequest) (*ServicesResponse, error)
}

func (s *CloudBillingService) getServices(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/cloudbilling.CloudBilling/GetServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetServices(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterCloudBillingService registers a service implementation with a gRPC server.
func RegisterCloudBillingService(s grpc.ServiceRegistrar, srv *CloudBillingService) {
	srvCopy := *srv
	if srvCopy.GetServices == nil {
		srvCopy.GetServices = func(context.Context, *ServicesRequest) (*ServicesResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetServices not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "cloudbilling.CloudBilling",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetServices",
				Handler:    srvCopy.getServices,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "pkg/cloudbilling/cloudbilling.proto",
	}

	s.RegisterService(&sd, nil)
}
